package(default_visibility = ["//visibility:public"])

cc_library(
    name = "defines",
    hdrs = [
        "defines.h",
    ],
)

cc_library(
    name = "io",
    hdrs = [
        "io.h",
    ],
    srcs = [
        "io.cc",
    ],
    deps = [
        "@glog",
        "@jsoncpp",
    ],
)
